registry:
  restart: always
  image: registry:2
  ports:
    - 55000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_AUTH: htpasswd
  volumes:
    - /opt/docker-registry/data:/var/lib/registry
    - /etc/docker/certs.d/registry:/certs
    - /opt/docker-registry/auth:/auth
