apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  ".dockercfg": "eyJodHRwczovL2xpbnV4LXhwMTM6NTUwMDAiOnsiYXV0aCI6IlpHOWphMlZ5ZFhObGNqcGtiMk5yWlhJeU1qTndZWE56ZDI5eVpBPT0iLCJlbWFpbCI6ImFsZXhhbmRlcmd1emh2YUBnbWFpbC5jb20ifX0="
type: kubernetes.io/dockercfg