server:
    applicationConnectors:
        - type: http
          port: 11020
    adminConnectors:
        - type: http
          port: 11021

simpleDownloaderParameters:
    serviceUrl: http://localhost:11090/


betterHTMLParserParameters:
    styles:
        - name: "html.html-schemius.html-adaptive"
          body: "article.b-singlepost-body.entry-content.e-content"
          comments: "div#comments.b-grove.b-grove-hover"
          description: "yer-sub"
        - name: "html.html-s2-no-adaptive"
          body: "div.entry-content"
          comments: "div#comments.entry-wrap.entry-comments"
          description: "crustgroup"
        - name: "html.html-s2-no-adaptive"
          body: "div.asset-body"
          comments: "div.comments-inner"
          description: "karleev"
        - name: "html.html-s2-no-adaptive"
          body: "div.entryText.s2-entrytext"
          comments: "div.comments-wrapper"
          description: "botalex"
        - name: "html-adaptive"
          body: "div.j-e-text"
          comments: "div#comments.j-l-comments"
          description: "enview"
        - name: "html-s2-no-adaptive"
          body: "div.entry-content"
          comments: ""
          description: "humus"

