server:
    applicationConnectors:
        - type: http
          port: 11170
    adminConnectors:
        - type: http
          port: 11171

processorParameters:
    calendarServiceUrl: "unused"
    processorIdentity:
        id: "ljagent"

downloadTaskClientParameters:
    serviceUrl: "http://localhost:11250/"

ljCalendarTaskClientParameters:
    serviceUrl: "http://localhost:11260/calendar/"

