server:
    applicationConnectors:
        - type: http
          port: 11170
    adminConnectors:
        - type: http
          port: 11171

processorParameters:
    processorIdentity:
        id: "ljagent"
    uploadServiceUrl: "http://localhost:11240/"

downloadTaskClientParameters:
    serviceUrl: "http://localhost:11250/"

ljCalendarTaskClientParameters:
    serviceUrl: "http://localhost:11260/calendar/"

processorManagerParameters:
    shutdownTimeoutMsec: 5000
    queueTimerRateMsec: 2000
