server:
    applicationConnectors:
        - type: http
          port: 11170
    adminConnectors:
        - type: http
          port: 11171

httpClient:
    timeout: 2000ms
    connectionTimeout: 2000ms
    connectionRequestTimeout: 2000ms

processorParameters:
    calendarServiceUrl: "http://localhost:11240/"
    processorIdentity:
        id: "ljagent"

downloadTaskClientParameters:
    serviceUrl: "http://localhost:11250/"

ljCalendarTaskClientParameters:
    serviceUrl: "http://localhost:11260/"

