server:
    applicationConnectors:
        - type: http
          port: 11220
    adminConnectors:
        - type: http
          port: 11221

singlePageClientParameters:
    serviceUrl: "http://localhost:11260/singlepage/"

calendarClientParameters:
    serviceUrl: "http://localhost:11260/calendar/"

